#image: k33g/gitpod-extism-playground:0.0.1
image: k33g/gitpod-simplism-playground:0.0.2

tasks:
    - name: install-simplism
      before: |
        SIMPLISM_DISTRO="Linux_x86_64" # 👀 https://github.com/bots-garden/simplism/releases
        VERSION="0.0.7"
        wget https://github.com/bots-garden/simplism/releases/download/v${VERSION}/simplism_${SIMPLISM_DISTRO}.tar.gz -O simplism.tar.gz 
        sudo tar -xf simplism.tar.gz -C /usr/bin
        rm simplism.tar.gz
        simplism version
        go mod tidy

vscode:
  extensions:
    - PKief.material-icon-theme
    - PKief.material-product-icons
    - aaron-bond.better-comments
    - golang.go
    - rust-lang.rust-analyzer

